name: Instagram Bot Tetikleyici
on:
  push:
    paths:
      - 'Gelen_Kutusu/**' # Müşteri buraya foto atınca çalışır
  workflow_dispatch: # Elinle başlatma butonu ekler

jobs:
  paylasim-yap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Kütüphaneleri Yükle
        run: |
          pip install playwright
          playwright install chromium
      - name: Botu Çalıştır
        env:
          IG_COOKIES: ${{ secrets.IG_COOKIES }}
        run: python bot.py
